# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -id {DRC MDRV-1}  -suppress 
set_msg_config  -id {Labtoolstcl 44-513}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/user/cours/PR209_MP3/Projects/Partie_2/Partie_2.cache/wt [current_project]
set_property parent.project_path /home/user/cours/PR209_MP3/Projects/Partie_2/Partie_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/user/cours/PR209_MP3/Projects/Partie_2/Partie_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/user/cours/PR209_MP3/src/Top_level_Partie2.vhd
  /home/user/cours/PR209_MP3/src/CE_gen_44100.vhd
  /home/user/cours/PR209_MP3/src/cpt_0_44099.vhd
  /home/user/cours/PR209_MP3/src/PWM.vhd
  /home/user/cours/PR209_MP3/src/uart/stop_counter.vhd
  /home/user/cours/PR209_MP3/src/uart/merger_8b_to_16b.vhd
  /home/user/cours/PR209_MP3/src/uart/full_uart_recv.vhd
  /home/user/cours/PR209_MP3/src/uart/uart_recv.vhd
  /home/user/cours/PR209_MP3/src/RAM.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/user/cours/PR209_MP3/Projects/Partie_2/Partie_2.srcs/constrs_1/new/nexys4.xdc
set_property used_in_implementation false [get_files /home/user/cours/PR209_MP3/Projects/Partie_2/Partie_2.srcs/constrs_1/new/nexys4.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_Level_Partie2 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Level_Partie2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Level_Partie2_utilization_synth.rpt -pb Top_Level_Partie2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
